version: '3'

services:

    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
          - ${PWD}/application:/var/www/html
          - ${PWD}/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      ports:
         - "8000:80"
  
    php:
      build: ./docker/php-fpm
      container_name: php
      working_dir: /var/www/html
      volumes:
          - ${PWD}/application:/var/www/html
          - ${PWD}/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
         
    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
          - MYSQL_ROOT_PASSWORD=pass
          - MYSQL_DATABASE=symfony
          - MYSQL_USER=newuser
          - MYSQL_PASSWORD=pass
